### ISSUE TITLE
if field not comprised in the list (method field()) she not comprised in the rest-dock

### ISSUE THREAD

**Issue by 4irik** [pahanini/yii2-rest-doc#12]
We have a class:

``` php
/**
 * A class.
 * 
 * @property int a `a` field 
 * @property int b `b` field
 * @property int c `c` field
 */
class A extends ActiveRecord {

  /**
   * @restdock-link a
   * @restdock-link b
   */
  public function fields()
  {
    return [
      'a',
      'b',
    ];
  }

  public function rules(){
    return [
      ['a', 'required'],
      ['c', 'required'],
    ];
  }
}
```

And we get documentation:
## Obaining record

| Attribute | Type | Description |
| --- | --- | --- |
| a | int | `a` field |
| b | int | `b` field |
## Create record

| Attribute | Type | Description |
| --- | --- | --- |
| a | int | `a` field |

As you can see documentation not contain `c` attribute in section `Create record`.

**Comment by thiagoarioli** [comment]
any new solution for this?

**Comment by pahanini** [comment]
It's not a bug. Only fields marked with restdoc-link or restdoc-filed appears in docs. Just add  `@restdock-link c`
