### ISSUE TITLE
Can't generate documentation.

### ISSUE THREAD

**Issue by kynamar** [pahanini/yii2-rest-doc#13]
When I run the command >php yii build-rest-doc, I do not get any error, but the generated html file is containing has the same content as the template(restdoc.twig).
What could cause this problem ? 

Thank you in advance.

**Comment by pahanini** [comment]
Try this solution
https://github.com/pahanini/yii2-rest-doc/issues/8

**Comment by kynamar** [comment]
Now I get the following error `Exception 'yii\base\InvalidCallException' with message 'Setting read-only property: yii\console\Application::view'`

**Comment by kynamar** [comment]
Problem solved. Thank you very much

**Comment by pahanini** [comment]
Welcome
