### ISSUE TITLE
Read Me is confusing

### ISSUE THREAD

**Issue by friek108** [pahanini/yii2-rest-doc#14]
As a noob in slate, api documentation & twig, the ReadMe doesn't explain how to set this up from scratch. I set up and configured this and it ran successfully, but just gives me some plain 'nice-documentation.html' file. Then what? Where do you put this? What do you do with it? What folder structure should I put this in considering my API is a module?

**Comment by pahanini** [comment]
Here the basic workflow:
1. Set up this lib and slate 
2. Create twig (or php) templates to generate .md file. Look at the slate repo for [example](https://github.com/lord/slate/blob/master/source/index.html.md).
3. Generate .md file using this lib
4. Use slate to generate 'nice-documentation.html' file.

Each time you build application repeat steps 3 and 4.

PS. If you have empty .md file at step 2 then you probably forgot to add twig extension.

**Comment by pahanini** [comment]
Here an example how to enable [twig](https://github.com/pahanini/yii2-rest-doc/issues/8)
